### ISSUE TITLE
New Event errors out if you don't select AM or PM... and I didn't know it wanted that

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/sandcal#8]
This is what I put in the form:
![image](https://user-images.githubusercontent.com/4399499/84605394-6f90a580-ae62-11ea-9f59-9ac9789bb6f9.png)

I just get a blank screen when I push the button. I get this in dev console:
![image](https://user-images.githubusercontent.com/4399499/84605407-9058fb00-ae62-11ea-8905-2354161be12d.png)

**Comment by ocdtrekkie** [comment]
Okay, so now I've figured out the final -- wanted AM or PM. I thought it might be seconds, and when I pushed 0 while highlighting that... it did nothing.

**Comment by zenhack** [comment]
Just pushed c0c4dd7, which makes it so that the create button stays greyed out until you fill in all the required info. There's probably room to make this better though, so I'm going to leave this open until we have the form giving better feedback.

I agree the time widgets are a little ambiguous; this is what I get for using the browsers' native elements? I don't really want to pull in some custom picker if I don't have to though...

**Comment by ocdtrekkie** [comment]
Can you put an example on the form? Had I seen the word AM or PM anywhere, I'd have realized what it wanted.

The other option would be to prepopulate the fields with a time. Then people would change it to what they want, but see what it is supposed to look like.

**Comment by zenhack** [comment]
Firefox doesn't seem to do anything with `placeholder` on time inputs, but I suppose we could just pre-fill the time fields with something semi-reasonable

**Comment by ocdtrekkie** [comment]
On my iPhone, a new calendar event is today around the current hour. I hit new at 7:48 PM and it was set from 7 to 8. I think that's reasonable?

And of course, if you check All Day event, it's going to disable/ignore that anyways, so it shouldn't be a huge burden to be prefilled that way.
